### ISSUE TITLE
Use composer.json to import librairies

### ISSUE THREAD

**Issue by 0ddlyoko** [RLoris/layer#2]
You should use **composer.json** to import librairies instead of adding them in this project (/src/lib)
By downloading this project, you'll have to enter `composer install` to install librairies that are in **composer.json** file.
A **vendor** directory will be created containing all librairies and a file named **autoload.php**. Just load this file and it's ok
> `require vendor/autoload.php`

**Comment by RLoris** [comment]
The annotation lib that I use is not on composer packagist, I will customize it in the future to be more flexible for my case, thus for the moment no need to import it from composer it works fine
